version: '3.8'

services:
  web:
    build: .
    image: rr:latest
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html

  db:
    image: mariadb:5.5
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_CHARSET: 'utf8'
      MYSQL_COLLATION: 'utf8_czech_ci'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
    command: [ 'mysqld', '--character-set-server=utf8', '--c  ollation-server=utf8_czech_ci' ]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: user
      PMA_PASSWORD: pass
    restart: always
    ports:
      - 8081:80
